name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check if package.json exists
        id: check-package
        run: |
          if [ -f "package.json" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        
      - name: Setup Node.js
        if: steps.check-package.outputs.exists == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        if: steps.check-package.outputs.exists == 'true'
        run: npm ci
        
      - name: Run linter
        if: steps.check-package.outputs.exists == 'true'
        run: npm run lint --if-present
        
      - name: Run tests
        if: steps.check-package.outputs.exists == 'true'
        run: npm test --if-present
        
      - name: Skip message
        if: steps.check-package.outputs.exists == 'false'
        run: echo "Skipping Node.js tests - package.json not found"
